var data_config = {
    tag: "visualization",
    mode: "local_files",

    title: "Overview of Openaire projects",
    input_format: "csv",
    base_unit: "readers",
    use_area_uri: false,
    is_force_areas: false,
    url_prefix: "",

    show_timeline: false,
    show_dropdown: true,
    show_intro: false,
    show_list:true,
    is_force_papers:true,

	show_context: false,
	create_title_from_context: false,

    files: [
 {file: './openaire/TU_GRAZ_RELYONIT.csv', title: 'TU_GRAZ_RELYONIT'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_DIPROMON.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_DIPROMON'},
 {file: './openaire/TU_GRAZ_WESPOT.csv', title: 'TU_GRAZ_WESPOT'},
 {file: './openaire/TU_GRAZ_BIOTRAINS.csv', title: 'TU_GRAZ_BIOTRAINS'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_ISTOPPFALLS.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_ISTOPPFALLS'},
 {file: './openaire/KNOW_EEXCESS.csv', title: 'KNOW_EEXCESS'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_HYRIM.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_HYRIM'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_POLLUX.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_POLLUX'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_ENCCA.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_ENCCA'},
 {file: './openaire/TU_GRAZ_ANIMPOL.csv', title: 'TU_GRAZ_ANIMPOL'},
 {file: './openaire/TU_GRAZ_CLINICIMPPACT.csv',
  title: 'TU_GRAZ_CLINICIMPPACT'},
 {file: './openaire/TU_GRAZ_GALA.csv', title: 'TU_GRAZ_GALA'},
 {file: './openaire/TU_GRAZ_COTTONBLEACH.csv',
  title: 'TU_GRAZ_COTTONBLEACH'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_EMC2.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_EMC2'},
 {file: './openaire/TU_GRAZ_BNCI HORIZON 2020.csv',
  title: 'TU_GRAZ_BNCI HORIZON 2020'},
 {file: './openaire/TU_GRAZ_NEXT-TELL.csv', title: 'TU_GRAZ_NEXT-TELL'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_FASTPASS.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_FASTPASS'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_GENESIS.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_GENESIS'},
 {file: './openaire/TU_GRAZ_DRIVE C2X.csv', title: 'TU_GRAZ_DRIVE C2X'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_SCAPE.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_SCAPE'},
 {file: './openaire/TU_GRAZ_OXYGEN.csv', title: 'TU_GRAZ_OXYGEN'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_SI-DRIVE.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_SI-DRIVE'},
 {file: './openaire/FWF_ERA-NET NEURON II.csv',
  title: 'FWF_ERA-NET NEURON II'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_SECCRIT.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_SECCRIT'},
 {file: './openaire/TU_GRAZ_INGAS.csv', title: 'TU_GRAZ_INGAS'},
 {file: './openaire/TU_GRAZ_BIOCOMES.csv', title: 'TU_GRAZ_BIOCOMES'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_COMPANIONABLE.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_COMPANIONABLE'},
 {file: './openaire/TU_GRAZ_ABC.csv', title: 'TU_GRAZ_ABC'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_VECOM.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_VECOM'},
 {file: './openaire/TU_GRAZ_ROLE.csv', title: 'TU_GRAZ_ROLE'},
 {file: './openaire/TU_GRAZ_MACSHEEP.csv', title: 'TU_GRAZ_MACSHEEP'},
 {file: './openaire/TU_GRAZ_COPPER.csv', title: 'TU_GRAZ_COPPER'},
 {file: './openaire/TU_GRAZ_COCONUT.csv', title: 'TU_GRAZ_COCONUT'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_SERVPPIN.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_SERVPPIN'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_SUDPLAN.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_SUDPLAN'},
 {file: './openaire/TU_GRAZ_TOBI.csv', title: 'TU_GRAZ_TOBI'},
 {file: './openaire/TU_GRAZ_DEWI.csv', title: 'TU_GRAZ_DEWI'},
 {file: './openaire/TU_GRAZ_ESTEEM 2.csv', title: 'TU_GRAZ_ESTEEM 2'},
 {file: './openaire/TU_GRAZ_SENSEOCEAN.csv', title: 'TU_GRAZ_SENSEOCEAN'},
 {file: './openaire/TU_GRAZ_REFINE.csv', title: 'TU_GRAZ_REFINE'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_CI-NERGY.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_CI-NERGY'},
 {file: './openaire/TU_GRAZ_NANOFOL.csv', title: 'TU_GRAZ_NANOFOL'},
 {file: './openaire/TU_GRAZ_EUMET.csv', title: 'TU_GRAZ_EUMET'},
 {file: './openaire/TU_GRAZ_MBAT.csv', title: 'TU_GRAZ_MBAT'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_RESOLVE.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_RESOLVE'},
 {file: './openaire/TU_GRAZ_MAS.csv', title: 'TU_GRAZ_MAS'},
 {file: './openaire/TU_GRAZ_FACETS-ITN.csv', title: 'TU_GRAZ_FACETS-ITN'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_ENVIROFI.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_ENVIROFI'},
 {file: './openaire/TU_GRAZ_FUTURE BNCI.csv',
  title: 'TU_GRAZ_FUTURE BNCI'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_GEOLAND2.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_GEOLAND2'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_CRISMA.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_CRISMA'},
 {file: './openaire/TU_GRAZ_IMREAL.csv', title: 'TU_GRAZ_IMREAL'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_NAMDIATREAM.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_NAMDIATREAM'},
 {file: './openaire/TU_GRAZ_TAMPRES.csv', title: 'TU_GRAZ_TAMPRES'},
 {file: './openaire/TU_GRAZ_BACKHOME.csv', title: 'TU_GRAZ_BACKHOME'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_NERA.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_NERA'},
 {file: './openaire/FWF_BIODIVERSA2.csv', title: 'FWF_BIODIVERSA2'},
 {file: './openaire/KNOW_STELLAR.csv', title: 'KNOW_STELLAR'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_MBAT.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_MBAT'},
 {file: './openaire/TU_GRAZ_ECRYPT II.csv', title: 'TU_GRAZ_ECRYPT II'},
 {file: './openaire/KNOW_MIRROR.csv', title: 'KNOW_MIRROR'},
 {file: './openaire/ZENTRUM_FUR_SOZIALE_INNOVATION_GMBH_EQUIP.csv',
  title: 'ZENTRUM_FUR_SOZIALE_INNOVATION_GMBH_EQUIP'},
 {file: './openaire/TU_GRAZ_TARGET.csv', title: 'TU_GRAZ_TARGET'},
 {file: './openaire/TU_GRAZ_MATURE.csv', title: 'TU_GRAZ_MATURE'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_CSI.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_CSI'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_GREENLAND.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_GREENLAND'},
 {file: './openaire/TU_GRAZ_HYDROSYS.csv', title: 'TU_GRAZ_HYDROSYS'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_AUTOCAST.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_AUTOCAST'},
 {file: './openaire/TU_GRAZ_OXYGREEN.csv', title: 'TU_GRAZ_OXYGREEN'},
 {file: './openaire/KNOW_SEMAGROW.csv', title: 'KNOW_SEMAGROW'},
 {file: './openaire/TU_GRAZ_LIPIDOMICNET.csv',
  title: 'TU_GRAZ_LIPIDOMICNET'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_FORESTTRAC.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_FORESTTRAC'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_TREES4FUTURE.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_TREES4FUTURE'},
 {file: './openaire/ZENTRUM_FUR_SOZIALE_INNOVATION_GMBH_SI-DRIVE.csv',
  title: 'ZENTRUM_FUR_SOZIALE_INNOVATION_GMBH_SI-DRIVE'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_GREENLION.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_GREENLION'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_CHEETAH.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_CHEETAH'},
 {file: './openaire/KNOW_AGINFRA.csv', title: 'KNOW_AGINFRA'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_ELECTRA.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_ELECTRA'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_NANOREG.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_NANOREG'},
 {file: './openaire/TU_GRAZ_VALCRI.csv', title: 'TU_GRAZ_VALCRI'},
 {file: './openaire/TU_GRAZ_TEAM.csv', title: 'TU_GRAZ_TEAM'},
 {file: './openaire/KNOW_GRASSMARGINS.csv', title: 'KNOW_GRASSMARGINS'},
 {file: './openaire/TU_GRAZ_ORGANIC.csv', title: 'TU_GRAZ_ORGANIC'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_UNCOVER.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_UNCOVER'},
 {file: './openaire/TU_GRAZ_NOVO.csv', title: 'TU_GRAZ_NOVO'},
 {file: './openaire/ZENTRUM_FUR_SOZIALE_INNOVATION_GMBH_STELLAR.csv',
  title: 'ZENTRUM_FUR_SOZIALE_INNOVATION_GMBH_STELLAR'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_DERRI.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_DERRI'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_CARONTE.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_CARONTE'},
 {file: './openaire/TU_GRAZ_LAYERS.csv', title: 'TU_GRAZ_LAYERS'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_ROD-SOL.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_ROD-SOL'},
 {file: './openaire/TU_GRAZ_BIOINTENSE.csv', title: 'TU_GRAZ_BIOINTENSE'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_EMORPH.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_EMORPH'},
 {file: './openaire/TU_GRAZ_3D-COFORM.csv', title: 'TU_GRAZ_3D-COFORM'},
 {file: './openaire/TU_GRAZ_CULTURA.csv', title: 'TU_GRAZ_CULTURA'},
 {file: './openaire/TU_GRAZ_DECODER.csv', title: 'TU_GRAZ_DECODER'},
 {file: './openaire/TU_GRAZ_MODERN.csv', title: 'TU_GRAZ_MODERN'},
 {file: './openaire/TU_GRAZ_GO-SMART.csv', title: 'TU_GRAZ_GO-SMART'},
 {file: './openaire/FWF_CHIST-ERA II.csv', title: 'FWF_CHIST-ERA II'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_TATOO.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_TATOO'},
 {file: './openaire/TU_GRAZ_SECOND ACT.csv', title: 'TU_GRAZ_SECOND ACT'},
 {file: './openaire/TU_GRAZ_CHEBANA.csv', title: 'TU_GRAZ_CHEBANA'},
 {file: './openaire/KNOW_EVAL-HEALTH.csv', title: 'KNOW_EVAL-HEALTH'},
 {file: './openaire/TU_GRAZ_RECOSY.csv', title: 'TU_GRAZ_RECOSY'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_EPICS.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_EPICS'},
 {file: './openaire/TU_GRAZ_BETTER.csv', title: 'TU_GRAZ_BETTER'},
 {file: './openaire/TU_GRAZ_AMARSI.csv', title: 'TU_GRAZ_AMARSI'},
 {file: './openaire/TU_GRAZ_COLOMBO.csv', title: 'TU_GRAZ_COLOMBO'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_SOPHIA.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_SOPHIA'},
 {file: './openaire/TU_GRAZ_NANOCATE.csv', title: 'TU_GRAZ_NANOCATE'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_SPARKS.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_SPARKS'},
 {file: './openaire/TU_GRAZ_BRAINABLE.csv', title: 'TU_GRAZ_BRAINABLE'},
 {file: './openaire/KNOW_CODE.csv', title: 'KNOW_CODE'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_VALORAM.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_VALORAM'},
 {file: './openaire/KNOW_WIQ-EI.csv', title: 'KNOW_WIQ-EI'},
 {file: './openaire/TU_GRAZ_SECO.csv', title: 'TU_GRAZ_SECO'},
 {file: './openaire/TU_GRAZ_SUDPLAN.csv', title: 'TU_GRAZ_SUDPLAN'},
 {file: './openaire/TU_GRAZ_BRAIN-I-NETS.csv',
  title: 'TU_GRAZ_BRAIN-I-NETS'},
 {file: './openaire/TU_GRAZ_THINFACE.csv', title: 'TU_GRAZ_THINFACE'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_EURIPIDES.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_EURIPIDES'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_REACCESS.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_REACCESS'},
 {file: './openaire/AIT_Austrian_Institute_of_Technology_GmbH_CRESSI.csv',
  title: 'AIT_Austrian_Institute_of_Technology_GmbH_CRESSI'}
]
};
