var data_config = {
    tag: "visualization",
    mode: "local_files",

    title: "Overview of Openaire projects",
    input_format: "csv",
    base_unit: "readers",
    use_area_uri: false,
    is_force_areas: false,
    url_prefix: "",

    show_timeline: false,
    show_dropdown: true,
    show_intro: false,
    show_list:true,
    is_force_papers:true,

	show_context: false,
	create_title_from_context: false,

    files: [
 {file: './openaire/TU GRAZ_ECRYPT II.csv', title: 'TU GRAZ_ECRYPT II'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_READY4SMARTCITIES.csv',
  title: 'AIT Austrian Institute of Technology GmbH_READY4SMARTCITIES'},
 {file: './openaire/TU GRAZ_PEBBLE.csv', title: 'TU GRAZ_PEBBLE'},
 {file: './openaire/TU GRAZ_BRAINSCALES.csv',
  title: 'TU GRAZ_BRAINSCALES'},
 {file: './openaire/TU GRAZ_GALA.csv', title: 'TU GRAZ_GALA'},
 {file: './openaire/TU GRAZ_MAS.csv', title: 'TU GRAZ_MAS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_PLANGRIDEV.csv',
  title: 'AIT Austrian Institute of Technology GmbH_PLANGRIDEV'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_SCAPE.csv',
  title: 'AIT Austrian Institute of Technology GmbH_SCAPE'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_NAMDIATREAM.csv',
  title: 'AIT Austrian Institute of Technology GmbH_NAMDIATREAM'},
 {file: './openaire/KNOW_EEXCESS.csv', title: 'KNOW_EEXCESS'},
 {file: './openaire/TU GRAZ_ALFA-BIRD.csv', title: 'TU GRAZ_ALFA-BIRD'},
 {file: './openaire/TU GRAZ_DIRHA.csv', title: 'TU GRAZ_DIRHA'},
 {file: './openaire/TU GRAZ_ANIMPOL.csv', title: 'TU GRAZ_ANIMPOL'},
 {file: './openaire/TU GRAZ_ARROWHEAD.csv', title: 'TU GRAZ_ARROWHEAD'},
 {file: './openaire/TU GRAZ_SCATH.csv', title: 'TU GRAZ_SCATH'},
 {file: './openaire/TU GRAZ_COLOMBO.csv', title: 'TU GRAZ_COLOMBO'},
 {file: './openaire/TU GRAZ_FUTUREID.csv', title: 'TU GRAZ_FUTUREID'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_VALORAM.csv',
  title: 'AIT Austrian Institute of Technology GmbH_VALORAM'},
 {file: './openaire/TU GRAZ_RECOSY.csv', title: 'TU GRAZ_RECOSY'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_EINS.csv',
  title: 'AIT Austrian Institute of Technology GmbH_EINS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_2-BE-SAFE.csv',
  title: 'AIT Austrian Institute of Technology GmbH_2-BE-SAFE'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ROD-SOL.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ROD-SOL'},
 {file: './openaire/TU GRAZ_CHOSEN.csv', title: 'TU GRAZ_CHOSEN'},
 {file: './openaire/TU GRAZ_CRYSTAL.csv', title: 'TU GRAZ_CRYSTAL'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_NANOREG.csv',
  title: 'AIT Austrian Institute of Technology GmbH_NANOREG'},
 {file: './openaire/TU GRAZ_COTTONBLEACH.csv',
  title: 'TU GRAZ_COTTONBLEACH'},
 {file: './openaire/TU GRAZ_RELYONIT.csv', title: 'TU GRAZ_RELYONIT'},
 {file: './openaire/TU GRAZ_TEAM.csv', title: 'TU GRAZ_TEAM'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ISTOPPFALLS.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ISTOPPFALLS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_EURHEALTHAGEING.csv',
  title: 'AIT Austrian Institute of Technology GmbH_EURHEALTHAGEING'},
 {file: './openaire/TU GRAZ_DIABAT.csv', title: 'TU GRAZ_DIABAT'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_VERA.csv',
  title: 'AIT Austrian Institute of Technology GmbH_VERA'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_SPARKS.csv',
  title: 'AIT Austrian Institute of Technology GmbH_SPARKS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_DIPROMON.csv',
  title: 'AIT Austrian Institute of Technology GmbH_DIPROMON'},
 {file: './openaire/TU GRAZ_ALICE.csv', title: 'TU GRAZ_ALICE'},
 {file: './openaire/TU GRAZ_VALCRI.csv', title: 'TU GRAZ_VALCRI'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_SOPHIA.csv',
  title: 'AIT Austrian Institute of Technology GmbH_SOPHIA'},
 {file: './openaire/FWF_ERA-NET NEURON II.csv',
  title: 'FWF_ERA-NET NEURON II'},
 {file: './openaire/ZENTRUM FUR SOZIALE INNOVATION GMBH_VERA.csv',
  title: 'ZENTRUM FUR SOZIALE INNOVATION GMBH_VERA'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_CRISMA.csv',
  title: 'AIT Austrian Institute of Technology GmbH_CRISMA'},
 {file: './openaire/TU GRAZ_ROLE.csv', title: 'TU GRAZ_ROLE'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_MBAT.csv',
  title: 'AIT Austrian Institute of Technology GmbH_MBAT'},
 {file: './openaire/ZENTRUM FUR SOZIALE INNOVATION GMBH_STELLAR.csv',
  title: 'ZENTRUM FUR SOZIALE INNOVATION GMBH_STELLAR'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_CITINES.csv',
  title: 'AIT Austrian Institute of Technology GmbH_CITINES'},
 {file: './openaire/TU GRAZ_TARGET.csv', title: 'TU GRAZ_TARGET'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_SPARD.csv',
  title: 'AIT Austrian Institute of Technology GmbH_SPARD'},
 {file: './openaire/TU GRAZ_UMBRELLA.csv', title: 'TU GRAZ_UMBRELLA'},
 {file: './openaire/TU GRAZ_DREAM.csv', title: 'TU GRAZ_DREAM'},
 {file: './openaire/TU GRAZ_MBAT.csv', title: 'TU GRAZ_MBAT'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_UNIVERSAAL.csv',
  title: 'AIT Austrian Institute of Technology GmbH_UNIVERSAAL'},
 {file: './openaire/TU GRAZ_CLINICIMPPACT.csv',
  title: 'TU GRAZ_CLINICIMPPACT'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ARROWHEAD.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ARROWHEAD'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ARDENT.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ARDENT'},
 {file: './openaire/TU GRAZ_OXYGREEN.csv', title: 'TU GRAZ_OXYGREEN'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_3D-LIGHTTRANS.csv',
  title: 'AIT Austrian Institute of Technology GmbH_3D-LIGHTTRANS'},
 {file: './openaire/TU GRAZ_MODERN.csv', title: 'TU GRAZ_MODERN'},
 {file: './openaire/TU GRAZ_NOVO.csv', title: 'TU GRAZ_NOVO'},
 {file: './openaire/TU GRAZ_DRIVE C2X.csv', title: 'TU GRAZ_DRIVE C2X'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_TATOO.csv',
  title: 'AIT Austrian Institute of Technology GmbH_TATOO'},
 {file: './openaire/TU GRAZ_EDAS.csv', title: 'TU GRAZ_EDAS'},
 {file: './openaire/TU GRAZ_BRAIN-I-NETS.csv',
  title: 'TU GRAZ_BRAIN-I-NETS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_HYRIM.csv',
  title: 'AIT Austrian Institute of Technology GmbH_HYRIM'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_DECOTESSC1.csv',
  title: 'AIT Austrian Institute of Technology GmbH_DECOTESSC1'},
 {file: './openaire/TU GRAZ_TOBI.csv', title: 'TU GRAZ_TOBI'},
 {file: './openaire/TU GRAZ_ASSESS.csv', title: 'TU GRAZ_ASSESS'},
 {file: './openaire/TU GRAZ_BIOINTENSE.csv', title: 'TU GRAZ_BIOINTENSE'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_HIPOW.csv',
  title: 'AIT Austrian Institute of Technology GmbH_HIPOW'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_COMPANIONABLE.csv',
  title: 'AIT Austrian Institute of Technology GmbH_COMPANIONABLE'},
 {file: './openaire/TU GRAZ_BIOTRAINS.csv', title: 'TU GRAZ_BIOTRAINS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_EMORPH.csv',
  title: 'AIT Austrian Institute of Technology GmbH_EMORPH'},
 {file: './openaire/KNOW_ALL-TIMES.csv', title: 'KNOW_ALL-TIMES'},
 {file: './openaire/TU GRAZ_OMNISCIENTIS.csv',
  title: 'TU GRAZ_OMNISCIENTIS'},
 {file: './openaire/TU GRAZ_WESPOT.csv', title: 'TU GRAZ_WESPOT'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ENVIROFI.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ENVIROFI'},
 {file: './openaire/TU GRAZ_BRAINABLE.csv', title: 'TU GRAZ_BRAINABLE'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_GENESIS.csv',
  title: 'AIT Austrian Institute of Technology GmbH_GENESIS'},
 {file: './openaire/TU GRAZ_IMPPACT.csv', title: 'TU GRAZ_IMPPACT'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_DRIVER.csv',
  title: 'AIT Austrian Institute of Technology GmbH_DRIVER'},
 {file: './openaire/TU GRAZ_ABC.csv', title: 'TU GRAZ_ABC'},
 {file: './openaire/TU GRAZ_THINFACE.csv', title: 'TU GRAZ_THINFACE'},
 {file: './openaire/TU GRAZ_BIOCOMES.csv', title: 'TU GRAZ_BIOCOMES'},
 {file: './openaire/TU GRAZ_NANOFOL.csv', title: 'TU GRAZ_NANOFOL'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ADOSE.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ADOSE'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_VECOM.csv',
  title: 'AIT Austrian Institute of Technology GmbH_VECOM'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_AUTOCAST.csv',
  title: 'AIT Austrian Institute of Technology GmbH_AUTOCAST'},
 {file: './openaire/TU GRAZ_LAYERS.csv', title: 'TU GRAZ_LAYERS'},
 {file: './openaire/ZENTRUM FUR SOZIALE INNOVATION GMBH_SI-DRIVE.csv',
  title: 'ZENTRUM FUR SOZIALE INNOVATION GMBH_SI-DRIVE'},
 {file: './openaire/TU GRAZ_SECO.csv', title: 'TU GRAZ_SECO'},
 {file: './openaire/TU GRAZ_AMARSI.csv', title: 'TU GRAZ_AMARSI'},
 {file: './openaire/TU GRAZ_EUMET.csv', title: 'TU GRAZ_EUMET'},
 {file: './openaire/TU GRAZ_REFINE.csv', title: 'TU GRAZ_REFINE'},
 {file: './openaire/TU GRAZ_LIPIDOMICNET.csv',
  title: 'TU GRAZ_LIPIDOMICNET'},
 {file: './openaire/TU GRAZ_COCONUT.csv', title: 'TU GRAZ_COCONUT'},
 {file: './openaire/FWF_BIODIVERSA2.csv', title: 'FWF_BIODIVERSA2'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_DOREMI.csv',
  title: 'AIT Austrian Institute of Technology GmbH_DOREMI'},
 {file: './openaire/TU GRAZ_ESTEEM 2.csv', title: 'TU GRAZ_ESTEEM 2'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_GREENLAND.csv',
  title: 'AIT Austrian Institute of Technology GmbH_GREENLAND'},
 {file: './openaire/KNOW_STELLAR.csv', title: 'KNOW_STELLAR'},
 {file: './openaire/TU GRAZ_GRAPPLE.csv', title: 'TU GRAZ_GRAPPLE'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_TEAM.csv',
  title: 'AIT Austrian Institute of Technology GmbH_TEAM'},
 {file: './openaire/TU GRAZ_CHEBANA.csv', title: 'TU GRAZ_CHEBANA'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_SUDPLAN.csv',
  title: 'AIT Austrian Institute of Technology GmbH_SUDPLAN'},
 {file: './openaire/KNOW_MIRROR.csv', title: 'KNOW_MIRROR'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_EPICS.csv',
  title: 'AIT Austrian Institute of Technology GmbH_EPICS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_POLLUX.csv',
  title: 'AIT Austrian Institute of Technology GmbH_POLLUX'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_MASELTOV.csv',
  title: 'AIT Austrian Institute of Technology GmbH_MASELTOV'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_NERA.csv',
  title: 'AIT Austrian Institute of Technology GmbH_NERA'},
 {file: './openaire/TU GRAZ_3D-COFORM.csv', title: 'TU GRAZ_3D-COFORM'},
 {file: './openaire/TU GRAZ_Z-ULTRA.csv', title: 'TU GRAZ_Z-ULTRA'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_FORESTTRAC.csv',
  title: 'AIT Austrian Institute of Technology GmbH_FORESTTRAC'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_RESOLVE.csv',
  title: 'AIT Austrian Institute of Technology GmbH_RESOLVE'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_UNCOVER.csv',
  title: 'AIT Austrian Institute of Technology GmbH_UNCOVER'},
 {file: './openaire/TU GRAZ_HYDROSYS.csv', title: 'TU GRAZ_HYDROSYS'},
 {file: './openaire/TU GRAZ_BRISK.csv', title: 'TU GRAZ_BRISK'},
 {file: './openaire/TU GRAZ_COPPER.csv', title: 'TU GRAZ_COPPER'},
 {file: './openaire/TU GRAZ_CAEC.csv', title: 'TU GRAZ_CAEC'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_FASTPASS.csv',
  title: 'AIT Austrian Institute of Technology GmbH_FASTPASS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ETCETERA.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ETCETERA'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_EUCARD.csv',
  title: 'AIT Austrian Institute of Technology GmbH_EUCARD'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_MOGENTES.csv',
  title: 'AIT Austrian Institute of Technology GmbH_MOGENTES'},
 {file: './openaire/KNOW_SEMAGROW.csv', title: 'KNOW_SEMAGROW'},
 {file: './openaire/TU GRAZ_OXYGEN.csv', title: 'TU GRAZ_OXYGEN'},
 {file: './openaire/TU GRAZ_SECOND ACT.csv', title: 'TU GRAZ_SECOND ACT'},
 {file: './openaire/TU GRAZ_CULTURA.csv', title: 'TU GRAZ_CULTURA'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ROSANNE.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ROSANNE'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_CHEETAH.csv',
  title: 'AIT Austrian Institute of Technology GmbH_CHEETAH'},
 {file: './openaire/TU GRAZ_TAMPRES.csv', title: 'TU GRAZ_TAMPRES'},
 {file: './openaire/TU GRAZ_SECRICOM.csv', title: 'TU GRAZ_SECRICOM'},
 {file: './openaire/TU GRAZ_DEWI.csv', title: 'TU GRAZ_DEWI'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_DERRI.csv',
  title: 'AIT Austrian Institute of Technology GmbH_DERRI'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_SECCRIT.csv',
  title: 'AIT Austrian Institute of Technology GmbH_SECCRIT'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_REACCESS.csv',
  title: 'AIT Austrian Institute of Technology GmbH_REACCESS'},
 {file: './openaire/KNOW_AGINFRA.csv', title: 'KNOW_AGINFRA'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_SERVPPIN.csv',
  title: 'AIT Austrian Institute of Technology GmbH_SERVPPIN'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_INNOSEC.csv',
  title: 'AIT Austrian Institute of Technology GmbH_INNOSEC'},
 {file: './openaire/TU GRAZ_SENSEOCEAN.csv', title: 'TU GRAZ_SENSEOCEAN'},
 {file: './openaire/TU GRAZ_HBP.csv', title: 'TU GRAZ_HBP'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_CI-NERGY.csv',
  title: 'AIT Austrian Institute of Technology GmbH_CI-NERGY'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_MUSES.csv',
  title: 'AIT Austrian Institute of Technology GmbH_MUSES'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_TREES4FUTURE.csv',
  title: 'AIT Austrian Institute of Technology GmbH_TREES4FUTURE'},
 {file: './openaire/TU GRAZ_NEXT-TELL.csv', title: 'TU GRAZ_NEXT-TELL'},
 {file: './openaire/KNOW_GRASSMARGINS.csv', title: 'KNOW_GRASSMARGINS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_CREAM.csv',
  title: 'AIT Austrian Institute of Technology GmbH_CREAM'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_CRYSTAL.csv',
  title: 'AIT Austrian Institute of Technology GmbH_CRYSTAL'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_CSI.csv',
  title: 'AIT Austrian Institute of Technology GmbH_CSI'},
 {file: './openaire/TU GRAZ_NANOCATE.csv', title: 'TU GRAZ_NANOCATE'},
 {file: './openaire/TU GRAZ_E-BRAINS.csv', title: 'TU GRAZ_E-BRAINS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_DBF.csv',
  title: 'AIT Austrian Institute of Technology GmbH_DBF'},
 {file: './openaire/TU GRAZ_FUTURE BNCI.csv',
  title: 'TU GRAZ_FUTURE BNCI'},
 {file: './openaire/TU GRAZ_DRAGON.csv', title: 'TU GRAZ_DRAGON'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_CRESSI.csv',
  title: 'AIT Austrian Institute of Technology GmbH_CRESSI'},
 {file: './openaire/TU GRAZ_DECODER.csv', title: 'TU GRAZ_DECODER'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ETTIS.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ETTIS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_CARONTE.csv',
  title: 'AIT Austrian Institute of Technology GmbH_CARONTE'},
 {file: './openaire/TU GRAZ_FACETS-ITN.csv', title: 'TU GRAZ_FACETS-ITN'},
 {file: './openaire/TU GRAZ_STANCE.csv', title: 'TU GRAZ_STANCE'},
 {file: './openaire/TU GRAZ_MACPLUS.csv', title: 'TU GRAZ_MACPLUS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ELECTRA.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ELECTRA'},
 {file: './openaire/TU GRAZ_IMREAL.csv', title: 'TU GRAZ_IMREAL'},
 {file: './openaire/TU GRAZ_DIAMOND.csv', title: 'TU GRAZ_DIAMOND'},
 {file: './openaire/TU GRAZ_INGAS.csv', title: 'TU GRAZ_INGAS'},
 {file: './openaire/TU GRAZ_MATURE.csv', title: 'TU GRAZ_MATURE'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ASPIS.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ASPIS'},
 {file: './openaire/TU GRAZ_BIOSURF.csv', title: 'TU GRAZ_BIOSURF'},
 {file: './openaire/FWF_CHIST-ERA II.csv', title: 'FWF_CHIST-ERA II'},
 {file: './openaire/TU GRAZ_BACKHOME.csv', title: 'TU GRAZ_BACKHOME'},
 {file: './openaire/TU GRAZ_MOGENTES.csv', title: 'TU GRAZ_MOGENTES'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_APPLICMA.csv',
  title: 'AIT Austrian Institute of Technology GmbH_APPLICMA'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_EURIPIDES.csv',
  title: 'AIT Austrian Institute of Technology GmbH_EURIPIDES'},
 {file: './openaire/KNOW_EVAL-HEALTH.csv', title: 'KNOW_EVAL-HEALTH'},
 {file: './openaire/TU GRAZ_SUDPLAN.csv', title: 'TU GRAZ_SUDPLAN'},
 {file: './openaire/KNOW_WESENSEIT.csv', title: 'KNOW_WESENSEIT'},
 {file: './openaire/TU GRAZ_MAINLINE.csv', title: 'TU GRAZ_MAINLINE'},
 {file: './openaire/TU GRAZ_GO-SMART.csv', title: 'TU GRAZ_GO-SMART'},
 {file: './openaire/TU GRAZ_BETTER.csv', title: 'TU GRAZ_BETTER'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_GREENLION.csv',
  title: 'AIT Austrian Institute of Technology GmbH_GREENLION'},
 {file: './openaire/KNOW_CODE.csv', title: 'KNOW_CODE'},
 {file: './openaire/TU GRAZ_BNCI HORIZON 2020.csv',
  title: 'TU GRAZ_BNCI HORIZON 2020'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ECOSSIAN.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ECOSSIAN'},
 {file: './openaire/ZENTRUM FUR SOZIALE INNOVATION GMBH_INTELLEO.csv',
  title: 'ZENTRUM FUR SOZIALE INNOVATION GMBH_INTELLEO'},
 {file: './openaire/KNOW_WIQ-EI.csv', title: 'KNOW_WIQ-EI'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_EMC2.csv',
  title: 'AIT Austrian Institute of Technology GmbH_EMC2'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_PARIS.csv',
  title: 'AIT Austrian Institute of Technology GmbH_PARIS'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_GEOLAND2.csv',
  title: 'AIT Austrian Institute of Technology GmbH_GEOLAND2'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ABLAMOD.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ABLAMOD'},
 {file: './openaire/TU GRAZ_MACSHEEP.csv', title: 'TU GRAZ_MACSHEEP'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_ENCCA.csv',
  title: 'AIT Austrian Institute of Technology GmbH_ENCCA'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_GRASP.csv',
  title: 'AIT Austrian Institute of Technology GmbH_GRASP'},
 {file: './openaire/TU GRAZ_ORGANIC.csv', title: 'TU GRAZ_ORGANIC'},
 {file: './openaire/ZENTRUM FUR SOZIALE INNOVATION GMBH_EQUIP.csv',
  title: 'ZENTRUM FUR SOZIALE INNOVATION GMBH_EQUIP'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_EVADER.csv',
  title: 'AIT Austrian Institute of Technology GmbH_EVADER'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_SI-DRIVE.csv',
  title: 'AIT Austrian Institute of Technology GmbH_SI-DRIVE'},
 {file: './openaire/AIT Austrian Institute of Technology GmbH_QUIESST.csv',
  title: 'AIT Austrian Institute of Technology GmbH_QUIESST'}
  ]
};
