# create a list of all installed packages
ip <- as.data.frame(installed.packages())
head(ip)
# if you use MRO, make sure that no packages in this library will be removed
ip <- subset(ip, !grepl("MRO", ip$LibPath))
# we don't want to remove base or recommended packages either\
ip <- ip[!(ip[,"Priority"] %in% c("base", "recommended")),]
# determine the library where the packages are installed
path.lib <- unique(ip$LibPath)
# create a vector with all the names of the packages you want to remove
pkgs.to.remove <- ip[,1]
head(pkgs.to.remove)
# remove the packages
sapply(pkgs.to.remove, remove.packages, lib = path.lib)

install.packages('curl')
install.packages('remotes')
install.packages('logging')
install.packages('arsenal')
remotes::install_url('https://cran.r-project.org/src/contrib/Archive/proxy/proxy_0.4-20.tar.gz')
remotes::install_url('https://cran.r-project.org/src/contrib/Archive/GMD/GMD_0.3.3.tar.gz')
remotes::install_url("https://cran.r-project.org/src/contrib/Archive/slam/slam_0.1-37.tar.gz")
install.packages('data.table')
install.packages('doParallel')
install.packages('ecodist')
install.packages("jaod")
install.packages('jsonlite')
install.packages('MASS')
install.packages('cluster')
install.packages('vegan')
install.packages('onehot')
install.packages('parfossil')
install.packages('stringi')
install.packages('stringdist')
install.packages('xml2')
install.packages('plyr')
install.packages('dplyr')
install.packages('tidyr')
install.packages('readr')
install.packages('rentrez')
install.packages('rplos')
install.packages('SnowballC')
install.packages('textcat')
install.packages('tibble')
install.packages('forcats')
remotes::install_version("tm", version = "0.6")
remotes::install_github("ropensci/rbace")
remotes::install_github("sckott/ropenaire")
remotes::install_github("ropensci/rAltmetric")
remotes::install_github("r-lib/async")
remotes::install_github("ropensci/rcrossref@async")
remotes::install_github("chreman/rcoreoa@description-filter")
remotes::install_github("chreman/solrium")
