# create a list of all installed packages
ip <- as.data.frame(installed.packages())
head(ip)
# if you use MRO, make sure that no packages in this library will be removed
ip <- subset(ip, !grepl("MRO", ip$LibPath))
# we don't want to remove base or recommended packages either\
ip <- ip[!(ip[,"Priority"] %in% c("base", "recommended")),]
# determine the library where the packages are installed
path.lib <- unique(ip$LibPath)
# create a vector with all the names of the packages you want to remove
pkgs.to.remove <- ip[,1]
head(pkgs.to.remove)
# remove the packages
sapply(pkgs.to.remove, remove.packages, lib = path.lib)

install.packages('curl', dependencies=TRUE)
install.packages('remotes', dependencies=TRUE)
install.packages('logging', dependencies=TRUE)
install.packages('arsenal', dependencies=TRUE)
remotes::install_url('https://cran.r-project.org/src/contrib/Archive/proxy/proxy_0.4-20.tar.gz', dependencies=TRUE)
remotes::install_url('https://cran.r-project.org/src/contrib/Archive/GMD/GMD_0.3.3.tar.gz', dependencies=TRUE)
remotes::install_url("https://cran.r-project.org/src/contrib/Archive/slam/slam_0.1-37.tar.gz", dependencies=TRUE)
install.packages('data.table', dependencies=TRUE)
install.packages('doParallel', dependencies=TRUE)
install.packages('ecodist', dependencies=TRUE)
install.packages("jaod", dependencies=TRUE)
install.packages('jsonlite', dependencies=TRUE)
install.packages('MASS', dependencies=TRUE)
install.packages('cluster', dependencies=TRUE)
install.packages('vegan', dependencies=TRUE)
install.packages('onehot', dependencies=TRUE)
install.packages('parfossil', dependencies=TRUE)
install.packages('plyr', dependencies=TRUE)
install.packages('dplyr', dependencies=TRUE)
install.packages('tidyr', dependencies=TRUE)
install.packages('rAltmetric', dependencies=TRUE)
install.packages('readr', dependencies=TRUE)
install.packages('rentrez', dependencies=TRUE)
install.packages('rplos', dependencies=TRUE)
install.packages('SnowballC', dependencies=TRUE)
install.packages('stringi', dependencies=TRUE)
install.packages('stringdist', dependencies=TRUE)
install.packages('textcat', dependencies=TRUE)
install.packages('textrank', dependencies=TRUE)
install.packages('tibble', dependencies=TRUE)
install.packages('forcats', dependencies=TRUE)
install.packages('xml2', dependencies=TRUE)
install.packages("BiocManager")
BiocManager::install("Rgraphviz")
remotes::install_url("https://datacube.wu.ac.at/src/contrib/Rcampdf_0.0-0.tar.gz", dependencies=TRUE)
remotes::install_version("tm", version = "0.6", dependencies=TRUE)
remotes::install_github("ropensci/rbace", dependencies=TRUE)
remotes::install_github("sckott/ropenaire", dependencies=TRUE)
remotes::install_github("ropensci/rAltmetric", dependencies=TRUE)
remotes::install_github("ropensci/rbace", dependencies=TRUE)
remotes::install_github("ropensci/rcrossref@async", dependencies=TRUE)
remotes::install_github("chreman/rcoreoa@description-filter", dependencies=TRUE)
remotes::install_github("chreman/solrium", dependencies=TRUE)
remotes::install_github("r-lib/async", dependencies=TRUE)
